name: devops app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: List Files
      run: |
        echo "Git Hub Actions Demo"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to production
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/devops:${{ github.sha }} .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/devops:${{ github.sha }}

#       - name: Deploy to Azure Web App
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: 'devops-demo'
#           publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
#           images: ${{ secrets.DOCKER_HUB_USERNAME }}/devops:${{ github.sha }}